name: quran_app
description: A new Flutter project.
publish_to: "none"

version: 1.0.9+9

environment:
  # sdk: ">=3.3.3 <4.0.0"
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons:
  flutter_local_notifications: ^19.3.0
  # platforms:
  #   linux:
  #     default_package: none
  intl:
  rxdart:
  flutter_bloc:

  sqflite: ^2.4.2
  path: ^1.9.0
  geolocator: ^13.0.4
  shared_preferences: ^2.5.3

  pdfx: ^2.9.2
  just_audio: ^0.10.4
  path_provider: ^2.1.5
  dio: ^5.8.0+1
  audio_video_progress_bar: ^2.0.3
  connectivity_plus: ^7.0.0
  adhan: ^2.0.0+1
  adhan_dart: ^1.1.2
  smooth_page_indicator:
  # timelines:
  carousel_slider:
  url_launcher: ^6.3.1
  flutter_phone_direct_caller: ^2.2.1
  flutter_contacts: ^2.0.0
  auto_size_text:
  logger:
  flutter_islamic_icons:
  dartz:
  get_it:
  flutter_downloader: ^1.12.0
  permission_handler: ^12.0.0+1
  video_player: ^2.10.0
  # in_app_update:
  gap:
  # bot_toast:
  cached_network_image: ^3.3.0
  flutter_screenutil: ^5.9.0
  # restart_app:
  flutter_timezone: ^4.1.1
  timezone:
  flutter_qiblah: ^3.1.0+1
  equatable: ^2.0.7
  smooth_sheets: ^0.10.2
  palette_generator_master: ^1.0.1
  share_plus: ^11.0.0
  fluttertoast: ^8.2.12
  skeletonizer: ^2.0.1
  geocoding: ^4.0.0
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  firebase_core: ^3.15.1
  firebase_remote_config: ^5.4.7
  package_info_plus: ^8.3.0
  flutter_svg: ^2.2.0
  pull_to_refresh: ^2.0.0
  cloud_firestore: ^5.6.12
  device_info_plus: ^11.5.0
  firebase_messaging: ^15.2.10
  lottie: ^3.3.1
  youtube_player_flutter: ^9.1.3
  flutter_staggered_grid_view: ^0.7.0
  uuid: ^4.5.1
  flutter_overlay_window: ^0.5.0
  home_widget: ^0.9.1

  quran_library:
    path: flutter_packages/quran_library
  device_preview: ^1.3.1
  carousel_slider_plus: ^7.1.1
  preload_page_view: ^0.2.0
  # ---------------------------------------

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  very_good_analysis: ^5.1.0
  flutter_gen_runner: ^5.11.0
  build_runner: ^2.6.0
  flutter_launcher_icons: ^0.14.3

  # flutter_native_splash: ^2.4.6

# flutter_native_splash:
#   color: "#ffffff" # خلفية شاشة البداية
#   image: assets/logo/splash_icon.png # لوجو التطبيق (مقاس 512x512 أو 1024x1024 png)
#   # branding: assets/branding.png     # شعار فرعي (اختياري - أسفل الشاشة)
#   # branding_mode: bottom             # وضع الشعار الفرعي (bottom أو center)
#   color_dark: "#000000" # خلفية للشاشة في المود الداكن
#   image_dark: assets/logo/splash_icon_dark.png # لوجو الوضع الداكن (اختياري)
#   # branding_dark: assets/branding_dark.png  # شعار فرعي داكن (اختياري)
#   android: true # تفعيل للأندرويد
#   ios: true # تفعيل للآيفون
#   android_gravity: center # محاذاة صورة اللوجو
#   ios_content_mode: scaleAspectFill # نمط ملء صورة اللوجو في iOS
#   fullscreen: true # لجعل الشاشة بالكامل Splash بدون status bar
#   web: false # عادة لا ينصح بتفعيل الويب مع المكتبة
#   android_12:
#     image: assets/logo/splash_icon.png
#     icon_background_color: "#ffffff"
#     image_dark: assets/logo/splash_icon_dark.png
#     icon_background_color_dark: "#000000"
#     # branding: assets/branding.png
#     # branding_dark: assets/branding_dark.png
#     color: "#ffffff"
#     color_dark: "#000000"
#     fullscreen: true

flutter_gen:
  output: lib/gen/
  line_length: 80
  integrations:
    image: true
    flutter_svg: true
    lottie: true
  assets:
    exclude:
      - assets/raw/**

flutter:
  assets:
    - assets/
    - assets/image/
    - assets/json/
    # - assets/pdf/
    - assets/athores/
    - assets/lang/
    - assets/logo/
    - assets/svg/
    - assets/lottie/
    - assets/svg/surah_name/
    # - assets/images/
    - assets/svg/hijri/
    - assets/svg/alwaqf/
    - assets/json/
    - assets/json/young_muslim/
    - assets/json/young_muslim/playlists/

  fonts:
    - family: ios-1
      fonts:
        - asset: assets/fonts/ios-1.ttf

    - family: ios-2
      fonts:
        - asset: assets/fonts/ios-2.ttf

    - family: ios-3
      fonts:
        - asset: assets/fonts/ios-3.otf
    - family: uthmanic
      fonts:
        - asset: assets/fonts/UthmanTN1_Ver10.otf

    - family: uthmanic2
      fonts:
        - asset: assets/fonts/UthmanicHafs_V20.ttf

    - family: kufi
      fonts:
        - asset: assets/fonts/Kufam-Italic-VariableFont_wght.ttf
          style: italic
        - asset: assets/fonts/Kufam-VariableFont_wght.ttf
          weight: 500
        - asset: assets/fonts/Kufam-Regular.ttf
          weight: 100

    - family: naskh
      fonts:
        - asset: assets/fonts/NotoNaskhArabic-VariableFont_wght.ttf

    - family: amiri_quran
      fonts:
        - asset: assets/fonts/amiri-quran-regular.ttf

    - family: Scheherazade
      fonts:
        - asset: assets/fonts/scheherazade-new-regular.ttf

  uses-material-design: true

flutter_launcher_icons:
  android: false
  ios: true
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  macos:
    generate: true
    image_path: "assets/images/logo.png"
  image_path: "assets/images/logo.png"
  remove_alpha_ios: true
  min_sdk_android: 21
