// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPboTwAeAYuVLUCrvvRl7CfmGiTOJCPec',
    appId: '1:673349646615:web:8943b087f72456ad575f52',
    messagingSenderId: '673349646615',
    projectId: 'ecommerce-nefko-e5fb3',
    authDomain: 'ecommerce-nefko-e5fb3.firebaseapp.com',
    storageBucket: 'ecommerce-nefko-e5fb3.firebasestorage.app',
    measurementId: 'G-G1ST9ELKC5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8U-Ac5dGcyr5MJi4deqW_4hN1w-J6B2g',
    appId: '1:673349646615:android:5188e42e61027157575f52',
    messagingSenderId: '673349646615',
    projectId: 'ecommerce-nefko-e5fb3',
    storageBucket: 'ecommerce-nefko-e5fb3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYCAssz1BMsUcydE66H62fFjwTWNPsuaA',
    appId: '1:673349646615:ios:50efb3f9df2657e0575f52',
    messagingSenderId: '673349646615',
    projectId: 'ecommerce-nefko-e5fb3',
    storageBucket: 'ecommerce-nefko-e5fb3.firebasestorage.app',
    iosBundleId: 'com.tamaneena.tamaneenaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYCAssz1BMsUcydE66H62fFjwTWNPsuaA',
    appId: '1:673349646615:ios:50efb3f9df2657e0575f52',
    messagingSenderId: '673349646615',
    projectId: 'ecommerce-nefko-e5fb3',
    storageBucket: 'ecommerce-nefko-e5fb3.firebasestorage.app',
    iosBundleId: 'com.tamaneena.tamaneenaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCatnpFuMfv0nvFedoe3sPWTnBeT-85kfg',
    appId: '1:673349646615:web:7c352e1c4030634f575f52',
    messagingSenderId: '673349646615',
    projectId: 'ecommerce-nefko-e5fb3',
    authDomain: 'ecommerce-nefko-e5fb3.firebaseapp.com',
    storageBucket: 'ecommerce-nefko-e5fb3.firebasestorage.app',
    measurementId: 'G-BSWT3FM07R',
  );
}
